/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = {
  _type: 'richText';
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type WebsitePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'websitePage';
};

export type Link = {
  _type: 'link';
  label: string;
  linkType: 'internal' | 'external';
  internalReference?: WebsitePageReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type PageSettings = {
  _type: 'pageSettings';
  hideNavigation?: boolean;
  hideFooter?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to: string;
  redirectType: '301' | '302' | '307' | '308';
};

export type FooterNavigation = {
  _id: string;
  _type: 'footerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  columns?: Array<{
    heading?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: 'column';
    _key: string;
  }>;
  copyright?: string;
};

export type HeaderNavigation = {
  _id: string;
  _type: 'headerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteDescription?: string;
  defaultOpenGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  organizationLegalName?: string;
  organizationUrl?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type WebsitePage = {
  _id: string;
  _type: 'websitePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sections?: Array<
    {
      _key: string;
    } & RichText
  >;
  pageSettings?: PageSettings;
  seo?: Seo;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichText
  | WebsitePageReference
  | Link
  | PageSettings
  | SanityImageAssetReference
  | Seo
  | Redirect
  | FooterNavigation
  | HeaderNavigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | WebsitePage
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: linkProjection
// Query: {  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}
export type LinkProjectionResult = {
  label: never;
  linkType: never;
  openInNewTab: never;
  href: null;
};

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: siteSettingsQuery
// Query: *[_id == $id && _type == "siteSettings"][0]{  _id,  _type,  siteName,  siteDescription,  defaultOpenGraphImage,  organizationLegalName,  organizationUrl}
export type SiteSettingsQueryResult = {
  _id: string;
  _type: 'siteSettings';
  siteName: string;
  siteDescription: string | null;
  defaultOpenGraphImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  organizationLegalName: string | null;
  organizationUrl: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: headerNavigationQuery
// Query: *[_id == $id && _type == "headerNavigation"][0]{  _id,  _type,  title,  links[]{  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}}
export type HeaderNavigationQueryResult = {
  _id: string;
  _type: 'headerNavigation';
  title: string;
  links: Array<{
    label: string;
    linkType: 'external' | 'internal';
    openInNewTab: boolean | null;
    href: string | null;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: footerNavigationQuery
// Query: *[_id == $id && _type == "footerNavigation"][0]{  _id,  _type,  title,  columns[]{    _key,    heading,    links[]{  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}  },  copyright}
export type FooterNavigationQueryResult = {
  _id: string;
  _type: 'footerNavigation';
  title: string;
  columns: Array<{
    _key: string;
    heading: string | null;
    links: Array<{
      label: string;
      linkType: 'external' | 'internal';
      openInNewTab: boolean | null;
      href: string | null;
    }> | null;
  }> | null;
  copyright: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: pageProjection
// Query: {  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    }  }}
export type PageProjectionResult = {
  _id: never;
  _type: never;
  title: never;
  slug: never;
  seo: never;
  pageSettings: never;
  sections: never;
};

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: homepageQuery
// Query: *[_id == $id && _type == "websitePage"][0]{  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    }  }}
export type HomepageQueryResult = {
  _id: string;
  _type: 'websitePage';
  title: string;
  slug: string;
  seo: Seo | null;
  pageSettings: PageSettings | null;
  sections: Array<{
    _type: 'richText';
    _key: string;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: websitePageBySlugQuery
// Query: *[_type == "websitePage" && slug.current == $slug && _id != $homepageId][0]{  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    }  }}
export type WebsitePageBySlugQueryResult = {
  _id: string;
  _type: 'websitePage';
  title: string;
  slug: string;
  seo: Seo | null;
  pageSettings: PageSettings | null;
  sections: Array<{
    _type: 'richText';
    _key: string;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: allNonHomepageSlugsQuery
// Query: *[_type == "websitePage" && defined(slug.current) && _id != $homepageId]{    "slug": slug.current  }
export type AllNonHomepageSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: allWebsitePagesForSitemapQuery
// Query: *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]    | order(_updatedAt desc) {    "slug": slug.current,    "lastModified": _updatedAt,    "isHomepage": _id == $homepageId  }
export type AllWebsitePagesForSitemapQueryResult = Array<{
  slug: string;
  lastModified: string;
  isHomepage: boolean;
}>;

// Source: ../web/src/lib/sanity/queries/redirects.ts
// Variable: allRedirectsQuery
// Query: *[_type == "redirect" && defined(from) && defined(to)]{    from,    to,    redirectType  }
export type AllRedirectsQueryResult = Array<{
  from: string;
  to: string;
  redirectType: '301' | '302' | '307' | '308';
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}': LinkProjectionResult;
    '*[_id == $id && _type == "siteSettings"][0]{\n  _id,\n  _type,\n  siteName,\n  siteDescription,\n  defaultOpenGraphImage,\n  organizationLegalName,\n  organizationUrl\n}': SiteSettingsQueryResult;
    '*[_id == $id && _type == "headerNavigation"][0]{\n  _id,\n  _type,\n  title,\n  links[]{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}\n}': HeaderNavigationQueryResult;
    '*[_id == $id && _type == "footerNavigation"][0]{\n  _id,\n  _type,\n  title,\n  columns[]{\n    _key,\n    heading,\n    links[]{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}\n  },\n  copyright\n}': FooterNavigationQueryResult;
    '{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    }\n  }\n}': PageProjectionResult;
    '*[_id == $id && _type == "websitePage"][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    }\n  }\n}': HomepageQueryResult;
    '\n  *[_type == "websitePage" && slug.current == $slug && _id != $homepageId][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    }\n  }\n}\n': WebsitePageBySlugQueryResult;
    '\n  *[_type == "websitePage" && defined(slug.current) && _id != $homepageId]{\n    "slug": slug.current\n  }\n': AllNonHomepageSlugsQueryResult;
    '\n  *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]\n    | order(_updatedAt desc) {\n    "slug": slug.current,\n    "lastModified": _updatedAt,\n    "isHomepage": _id == $homepageId\n  }\n': AllWebsitePagesForSitemapQueryResult;
    '\n  *[_type == "redirect" && defined(from) && defined(to)]{\n    from,\n    to,\n    redirectType\n  }\n': AllRedirectsQueryResult;
  }
}
