/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SmsBanner = {
  _type: 'smsBanner';
  headline: string;
  body?: string;
  phoneNumber: string;
  phoneDisplay: string;
};

export type DepositCallout = {
  _type: 'depositCallout';
  eyebrow?: string;
  heading: string;
  body?: string;
  depositAmount: string;
  depositLabel?: string;
  depositNote?: string;
  reasons?: Array<{
    icon?:
      | 'phone'
      | 'map-pin'
      | 'navigation'
      | 'clock'
      | 'wrench'
      | 'check'
      | 'check-circle'
      | 'arrow-right'
      | 'star'
      | 'shield'
      | 'truck'
      | 'alert-triangle'
      | 'dollar-sign'
      | 'message'
      | 'gauge';
    title: string;
    description?: string;
    _type: 'depositReason';
    _key: string;
  }>;
};

export type CoverageSection = {
  _type: 'coverageSection';
  eyebrow?: string;
  heading: string;
  body?: string;
  towns: Array<string>;
};

export type ReviewsSection = {
  _type: 'reviewsSection';
  eyebrow?: string;
  heading: string;
  rating: number;
  reviewCount: number;
  quotes: Array<{
    quote: string;
    name: string;
    city?: string;
    _type: 'reviewQuote';
    _key: string;
  }>;
};

export type HowItWorks = {
  _type: 'howItWorks';
  eyebrow?: string;
  heading: string;
  steps: Array<{
    title: string;
    description?: string;
    _type: 'step';
    _key: string;
  }>;
};

export type ServicesSection = {
  _type: 'servicesSection';
  eyebrow?: string;
  heading: string;
  services: Array<{
    icon?:
      | 'phone'
      | 'map-pin'
      | 'navigation'
      | 'clock'
      | 'wrench'
      | 'check'
      | 'check-circle'
      | 'arrow-right'
      | 'star'
      | 'shield'
      | 'truck'
      | 'alert-triangle'
      | 'dollar-sign'
      | 'message'
      | 'gauge';
    title: string;
    description?: string;
    price?: string;
    _type: 'serviceItem';
    _key: string;
  }>;
};

export type TrustBar = {
  _type: 'trustBar';
  items: Array<{
    icon?:
      | 'phone'
      | 'map-pin'
      | 'navigation'
      | 'clock'
      | 'wrench'
      | 'check'
      | 'check-circle'
      | 'arrow-right'
      | 'star'
      | 'shield'
      | 'truck'
      | 'alert-triangle'
      | 'dollar-sign'
      | 'message'
      | 'gauge';
    value: string;
    label: string;
    _type: 'trustBarItem';
    _key: string;
  }>;
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headlineMain: string;
  headlineAccent: string;
  body?: string;
  trustMarkers?: Array<{
    icon?:
      | 'phone'
      | 'map-pin'
      | 'navigation'
      | 'clock'
      | 'wrench'
      | 'check'
      | 'check-circle'
      | 'arrow-right'
      | 'star'
      | 'shield'
      | 'truck'
      | 'alert-triangle'
      | 'dollar-sign'
      | 'message'
      | 'gauge';
    value: string;
    label: string;
    _type: 'trustMarker';
    _key: string;
  }>;
};

export type RichText = {
  _type: 'richText';
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type WebsitePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'websitePage';
};

export type Link = {
  _type: 'link';
  label: string;
  linkType: 'internal' | 'external';
  internalReference?: WebsitePageReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type PageSettings = {
  _type: 'pageSettings';
  hideNavigation?: boolean;
  hideFooter?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to: string;
  redirectType: '301' | '302' | '307' | '308';
};

export type FooterNavigation = {
  _id: string;
  _type: 'footerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  columns?: Array<{
    heading?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: 'column';
    _key: string;
  }>;
  copyright?: string;
};

export type HeaderNavigation = {
  _id: string;
  _type: 'headerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteDescription?: string;
  defaultOpenGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  organizationLegalName?: string;
  organizationUrl?: string;
  blogEnabled?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BlogPost = {
  _id: string;
  _type: 'blogPost';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  publishedAt: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type WebsitePage = {
  _id: string;
  _type: 'websitePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & TrustBar)
    | ({
        _key: string;
      } & ServicesSection)
    | ({
        _key: string;
      } & HowItWorks)
    | ({
        _key: string;
      } & ReviewsSection)
    | ({
        _key: string;
      } & CoverageSection)
    | ({
        _key: string;
      } & DepositCallout)
    | ({
        _key: string;
      } & SmsBanner)
  >;
  pageSettings?: PageSettings;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SmsBanner
  | DepositCallout
  | CoverageSection
  | ReviewsSection
  | HowItWorks
  | ServicesSection
  | TrustBar
  | HeroSection
  | RichText
  | WebsitePageReference
  | Link
  | PageSettings
  | SanityImageAssetReference
  | Seo
  | Redirect
  | FooterNavigation
  | HeaderNavigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | BlogPost
  | Slug
  | WebsitePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries/blog.ts
// Variable: allBlogPostsQuery
// Query: *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc) {    _id,    _type,    title,    "slug": slug.current,    excerpt,    coverImage,    publishedAt  }
export type AllBlogPostsQueryResult = Array<{
  _id: string;
  _type: 'blogPost';
  title: string;
  slug: string;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  publishedAt: string;
}>;

// Source: ../web/src/lib/sanity/queries/blog.ts
// Variable: blogPostBySlugQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    excerpt,    coverImage,    publishedAt,    body,    seo  }
export type BlogPostBySlugQueryResult = {
  _id: string;
  _type: 'blogPost';
  title: string;
  slug: string;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  publishedAt: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  seo: Seo | null;
} | null;

// Source: ../web/src/lib/sanity/queries/blog.ts
// Variable: allBlogPostSlugsQuery
// Query: *[_type == "blogPost" && defined(slug.current)]{    "slug": slug.current  }
export type AllBlogPostSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: ../web/src/lib/sanity/queries/blog.ts
// Variable: blogPostsForSitemapQuery
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishedAt) && seo.noIndex != true]    | order(_updatedAt desc) {    "slug": slug.current,    "lastModified": _updatedAt  }
export type BlogPostsForSitemapQueryResult = Array<{
  slug: string;
  lastModified: string;
}>;

// Source: ../web/src/lib/sanity/queries/blog.ts
// Variable: blogEnabledQuery
// Query: *[_id == $id && _type == "siteSettings"][0].blogEnabled
export type BlogEnabledQueryResult = boolean | null;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: linkProjection
// Query: {  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}
export type LinkProjectionResult = {
  label: never;
  linkType: never;
  openInNewTab: never;
  href: null;
};

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: siteSettingsQuery
// Query: *[_id == $id && _type == "siteSettings"][0]{  _id,  _type,  siteName,  siteDescription,  defaultOpenGraphImage,  organizationLegalName,  organizationUrl,  blogEnabled}
export type SiteSettingsQueryResult = {
  _id: string;
  _type: 'siteSettings';
  siteName: string;
  siteDescription: string | null;
  defaultOpenGraphImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  organizationLegalName: string | null;
  organizationUrl: string | null;
  blogEnabled: boolean | null;
} | null;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: headerNavigationQuery
// Query: *[_id == $id && _type == "headerNavigation"][0]{  _id,  _type,  title,  links[]{  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}}
export type HeaderNavigationQueryResult = {
  _id: string;
  _type: 'headerNavigation';
  title: string;
  links: Array<{
    label: string;
    linkType: 'external' | 'internal';
    openInNewTab: boolean | null;
    href: string | null;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/global.ts
// Variable: footerNavigationQuery
// Query: *[_id == $id && _type == "footerNavigation"][0]{  _id,  _type,  title,  columns[]{    _key,    heading,    links[]{  label,  linkType,  openInNewTab,  "href": select(    linkType == "external" => externalUrl,    linkType == "internal" => "/" + internalReference->slug.current,    null  )}  },  copyright}
export type FooterNavigationQueryResult = {
  _id: string;
  _type: 'footerNavigation';
  title: string;
  columns: Array<{
    _key: string;
    heading: string | null;
    links: Array<{
      label: string;
      linkType: 'external' | 'internal';
      openInNewTab: boolean | null;
      href: string | null;
    }> | null;
  }> | null;
  copyright: string | null;
} | null;

// Source: ../web/src/lib/sanity/queries/llms.ts
// Variable: siteSettingsForLlmsQuery
// Query: *[_id == $id && _type == "siteSettings"][0]{  siteName,  siteDescription,  blogEnabled}
export type SiteSettingsForLlmsQueryResult = {
  siteName: string;
  siteDescription: string | null;
  blogEnabled: boolean | null;
} | null;

// Source: ../web/src/lib/sanity/queries/llms.ts
// Variable: pagesForLlmsQuery
// Query: *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]{    title,    "slug": slug.current,    "isHomepage": _id == $homepageId  }
export type PagesForLlmsQueryResult = Array<{
  title: string;
  slug: string;
  isHomepage: boolean;
}>;

// Source: ../web/src/lib/sanity/queries/llms.ts
// Variable: blogPostsForLlmsQuery
// Query: *[_type == "blogPost" && defined(slug.current) && seo.noIndex != true]    | order(publishedAt desc) {    title,    "slug": slug.current,    excerpt  }
export type BlogPostsForLlmsQueryResult = Array<{
  title: string;
  slug: string;
  excerpt: string;
}>;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: pageProjection
// Query: {  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    },    _type == "heroSection" => {      eyebrow,      headlineMain,      headlineAccent,      body,      trustMarkers[]{ icon, value, label }    },    _type == "trustBar" => {      items[]{ icon, value, label }    },    _type == "servicesSection" => {      eyebrow,      heading,      services[]{ icon, title, description, price }    },    _type == "howItWorks" => {      eyebrow,      heading,      steps[]{ title, description }    },    _type == "reviewsSection" => {      eyebrow,      heading,      rating,      reviewCount,      quotes[]{ quote, name, city }    },    _type == "coverageSection" => {      eyebrow,      heading,      body,      towns    },    _type == "depositCallout" => {      eyebrow,      heading,      body,      depositAmount,      depositLabel,      depositNote,      reasons[]{ icon, title, description }    },    _type == "smsBanner" => {      headline,      body,      phoneNumber,      phoneDisplay    }  }}
export type PageProjectionResult = {
  _id: never;
  _type: never;
  title: never;
  slug: never;
  seo: never;
  pageSettings: never;
  sections: never;
};

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: homepageQuery
// Query: *[_id == $id && _type == "websitePage"][0]{  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    },    _type == "heroSection" => {      eyebrow,      headlineMain,      headlineAccent,      body,      trustMarkers[]{ icon, value, label }    },    _type == "trustBar" => {      items[]{ icon, value, label }    },    _type == "servicesSection" => {      eyebrow,      heading,      services[]{ icon, title, description, price }    },    _type == "howItWorks" => {      eyebrow,      heading,      steps[]{ title, description }    },    _type == "reviewsSection" => {      eyebrow,      heading,      rating,      reviewCount,      quotes[]{ quote, name, city }    },    _type == "coverageSection" => {      eyebrow,      heading,      body,      towns    },    _type == "depositCallout" => {      eyebrow,      heading,      body,      depositAmount,      depositLabel,      depositNote,      reasons[]{ icon, title, description }    },    _type == "smsBanner" => {      headline,      body,      phoneNumber,      phoneDisplay    }  }}
export type HomepageQueryResult = {
  _id: string;
  _type: 'websitePage';
  title: string;
  slug: string;
  seo: Seo | null;
  pageSettings: PageSettings | null;
  sections: Array<
    | {
        _type: 'coverageSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        body: string | null;
        towns: Array<string>;
      }
    | {
        _type: 'depositCallout';
        _key: string;
        eyebrow: string | null;
        heading: string;
        body: string | null;
        depositAmount: string;
        depositLabel: string | null;
        depositNote: string | null;
        reasons: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          title: string;
          description: string | null;
        }> | null;
      }
    | {
        _type: 'heroSection';
        _key: string;
        eyebrow: string | null;
        headlineMain: string;
        headlineAccent: string;
        body: string | null;
        trustMarkers: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          value: string;
          label: string;
        }> | null;
      }
    | {
        _type: 'howItWorks';
        _key: string;
        eyebrow: string | null;
        heading: string;
        steps: Array<{
          title: string;
          description: string | null;
        }>;
      }
    | {
        _type: 'reviewsSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        rating: number;
        reviewCount: number;
        quotes: Array<{
          quote: string;
          name: string;
          city: string | null;
        }>;
      }
    | {
        _type: 'richText';
        _key: string;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
      }
    | {
        _type: 'servicesSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        services: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          title: string;
          description: string | null;
          price: string | null;
        }>;
      }
    | {
        _type: 'smsBanner';
        _key: string;
        headline: string;
        body: string | null;
        phoneNumber: string;
        phoneDisplay: string;
      }
    | {
        _type: 'trustBar';
        _key: string;
        items: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          value: string;
          label: string;
        }>;
      }
  > | null;
} | null;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: websitePageBySlugQuery
// Query: *[_type == "websitePage" && slug.current == $slug && _id != $homepageId][0]{  _id,  _type,  title,  "slug": slug.current,  seo,  pageSettings,  sections[]{    _type,    _key,    _type == "richText" => {      body    },    _type == "heroSection" => {      eyebrow,      headlineMain,      headlineAccent,      body,      trustMarkers[]{ icon, value, label }    },    _type == "trustBar" => {      items[]{ icon, value, label }    },    _type == "servicesSection" => {      eyebrow,      heading,      services[]{ icon, title, description, price }    },    _type == "howItWorks" => {      eyebrow,      heading,      steps[]{ title, description }    },    _type == "reviewsSection" => {      eyebrow,      heading,      rating,      reviewCount,      quotes[]{ quote, name, city }    },    _type == "coverageSection" => {      eyebrow,      heading,      body,      towns    },    _type == "depositCallout" => {      eyebrow,      heading,      body,      depositAmount,      depositLabel,      depositNote,      reasons[]{ icon, title, description }    },    _type == "smsBanner" => {      headline,      body,      phoneNumber,      phoneDisplay    }  }}
export type WebsitePageBySlugQueryResult = {
  _id: string;
  _type: 'websitePage';
  title: string;
  slug: string;
  seo: Seo | null;
  pageSettings: PageSettings | null;
  sections: Array<
    | {
        _type: 'coverageSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        body: string | null;
        towns: Array<string>;
      }
    | {
        _type: 'depositCallout';
        _key: string;
        eyebrow: string | null;
        heading: string;
        body: string | null;
        depositAmount: string;
        depositLabel: string | null;
        depositNote: string | null;
        reasons: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          title: string;
          description: string | null;
        }> | null;
      }
    | {
        _type: 'heroSection';
        _key: string;
        eyebrow: string | null;
        headlineMain: string;
        headlineAccent: string;
        body: string | null;
        trustMarkers: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          value: string;
          label: string;
        }> | null;
      }
    | {
        _type: 'howItWorks';
        _key: string;
        eyebrow: string | null;
        heading: string;
        steps: Array<{
          title: string;
          description: string | null;
        }>;
      }
    | {
        _type: 'reviewsSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        rating: number;
        reviewCount: number;
        quotes: Array<{
          quote: string;
          name: string;
          city: string | null;
        }>;
      }
    | {
        _type: 'richText';
        _key: string;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
      }
    | {
        _type: 'servicesSection';
        _key: string;
        eyebrow: string | null;
        heading: string;
        services: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          title: string;
          description: string | null;
          price: string | null;
        }>;
      }
    | {
        _type: 'smsBanner';
        _key: string;
        headline: string;
        body: string | null;
        phoneNumber: string;
        phoneDisplay: string;
      }
    | {
        _type: 'trustBar';
        _key: string;
        items: Array<{
          icon:
            | 'alert-triangle'
            | 'arrow-right'
            | 'check-circle'
            | 'check'
            | 'clock'
            | 'dollar-sign'
            | 'gauge'
            | 'map-pin'
            | 'message'
            | 'navigation'
            | 'phone'
            | 'shield'
            | 'star'
            | 'truck'
            | 'wrench'
            | null;
          value: string;
          label: string;
        }>;
      }
  > | null;
} | null;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: allNonHomepageSlugsQuery
// Query: *[_type == "websitePage" && defined(slug.current) && _id != $homepageId]{    "slug": slug.current  }
export type AllNonHomepageSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: ../web/src/lib/sanity/queries/page.ts
// Variable: allWebsitePagesForSitemapQuery
// Query: *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]    | order(_updatedAt desc) {    "slug": slug.current,    "lastModified": _updatedAt,    "isHomepage": _id == $homepageId  }
export type AllWebsitePagesForSitemapQueryResult = Array<{
  slug: string;
  lastModified: string;
  isHomepage: boolean;
}>;

// Source: ../web/src/lib/sanity/queries/redirects.ts
// Variable: allRedirectsQuery
// Query: *[_type == "redirect" && defined(from) && defined(to)]{    from,    to,    redirectType  }
export type AllRedirectsQueryResult = Array<{
  from: string;
  to: string;
  redirectType: '301' | '302' | '307' | '308';
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    publishedAt\n  }\n': AllBlogPostsQueryResult;
    '\n  *[_type == "blogPost" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    publishedAt,\n    body,\n    seo\n  }\n': BlogPostBySlugQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': AllBlogPostSlugsQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishedAt) && seo.noIndex != true]\n    | order(_updatedAt desc) {\n    "slug": slug.current,\n    "lastModified": _updatedAt\n  }\n': BlogPostsForSitemapQueryResult;
    '*[_id == $id && _type == "siteSettings"][0].blogEnabled': BlogEnabledQueryResult;
    '{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}': LinkProjectionResult;
    '*[_id == $id && _type == "siteSettings"][0]{\n  _id,\n  _type,\n  siteName,\n  siteDescription,\n  defaultOpenGraphImage,\n  organizationLegalName,\n  organizationUrl,\n  blogEnabled\n}': SiteSettingsQueryResult;
    '*[_id == $id && _type == "headerNavigation"][0]{\n  _id,\n  _type,\n  title,\n  links[]{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}\n}': HeaderNavigationQueryResult;
    '*[_id == $id && _type == "footerNavigation"][0]{\n  _id,\n  _type,\n  title,\n  columns[]{\n    _key,\n    heading,\n    links[]{\n  label,\n  linkType,\n  openInNewTab,\n  "href": select(\n    linkType == "external" => externalUrl,\n    linkType == "internal" => "/" + internalReference->slug.current,\n    null\n  )\n}\n  },\n  copyright\n}': FooterNavigationQueryResult;
    '*[_id == $id && _type == "siteSettings"][0]{\n  siteName,\n  siteDescription,\n  blogEnabled\n}': SiteSettingsForLlmsQueryResult;
    '\n  *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]{\n    title,\n    "slug": slug.current,\n    "isHomepage": _id == $homepageId\n  }\n': PagesForLlmsQueryResult;
    '\n  *[_type == "blogPost" && defined(slug.current) && seo.noIndex != true]\n    | order(publishedAt desc) {\n    title,\n    "slug": slug.current,\n    excerpt\n  }\n': BlogPostsForLlmsQueryResult;
    '{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    },\n    _type == "heroSection" => {\n      eyebrow,\n      headlineMain,\n      headlineAccent,\n      body,\n      trustMarkers[]{ icon, value, label }\n    },\n    _type == "trustBar" => {\n      items[]{ icon, value, label }\n    },\n    _type == "servicesSection" => {\n      eyebrow,\n      heading,\n      services[]{ icon, title, description, price }\n    },\n    _type == "howItWorks" => {\n      eyebrow,\n      heading,\n      steps[]{ title, description }\n    },\n    _type == "reviewsSection" => {\n      eyebrow,\n      heading,\n      rating,\n      reviewCount,\n      quotes[]{ quote, name, city }\n    },\n    _type == "coverageSection" => {\n      eyebrow,\n      heading,\n      body,\n      towns\n    },\n    _type == "depositCallout" => {\n      eyebrow,\n      heading,\n      body,\n      depositAmount,\n      depositLabel,\n      depositNote,\n      reasons[]{ icon, title, description }\n    },\n    _type == "smsBanner" => {\n      headline,\n      body,\n      phoneNumber,\n      phoneDisplay\n    }\n  }\n}': PageProjectionResult;
    '*[_id == $id && _type == "websitePage"][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    },\n    _type == "heroSection" => {\n      eyebrow,\n      headlineMain,\n      headlineAccent,\n      body,\n      trustMarkers[]{ icon, value, label }\n    },\n    _type == "trustBar" => {\n      items[]{ icon, value, label }\n    },\n    _type == "servicesSection" => {\n      eyebrow,\n      heading,\n      services[]{ icon, title, description, price }\n    },\n    _type == "howItWorks" => {\n      eyebrow,\n      heading,\n      steps[]{ title, description }\n    },\n    _type == "reviewsSection" => {\n      eyebrow,\n      heading,\n      rating,\n      reviewCount,\n      quotes[]{ quote, name, city }\n    },\n    _type == "coverageSection" => {\n      eyebrow,\n      heading,\n      body,\n      towns\n    },\n    _type == "depositCallout" => {\n      eyebrow,\n      heading,\n      body,\n      depositAmount,\n      depositLabel,\n      depositNote,\n      reasons[]{ icon, title, description }\n    },\n    _type == "smsBanner" => {\n      headline,\n      body,\n      phoneNumber,\n      phoneDisplay\n    }\n  }\n}': HomepageQueryResult;
    '\n  *[_type == "websitePage" && slug.current == $slug && _id != $homepageId][0]{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  seo,\n  pageSettings,\n  sections[]{\n    _type,\n    _key,\n    _type == "richText" => {\n      body\n    },\n    _type == "heroSection" => {\n      eyebrow,\n      headlineMain,\n      headlineAccent,\n      body,\n      trustMarkers[]{ icon, value, label }\n    },\n    _type == "trustBar" => {\n      items[]{ icon, value, label }\n    },\n    _type == "servicesSection" => {\n      eyebrow,\n      heading,\n      services[]{ icon, title, description, price }\n    },\n    _type == "howItWorks" => {\n      eyebrow,\n      heading,\n      steps[]{ title, description }\n    },\n    _type == "reviewsSection" => {\n      eyebrow,\n      heading,\n      rating,\n      reviewCount,\n      quotes[]{ quote, name, city }\n    },\n    _type == "coverageSection" => {\n      eyebrow,\n      heading,\n      body,\n      towns\n    },\n    _type == "depositCallout" => {\n      eyebrow,\n      heading,\n      body,\n      depositAmount,\n      depositLabel,\n      depositNote,\n      reasons[]{ icon, title, description }\n    },\n    _type == "smsBanner" => {\n      headline,\n      body,\n      phoneNumber,\n      phoneDisplay\n    }\n  }\n}\n': WebsitePageBySlugQueryResult;
    '\n  *[_type == "websitePage" && defined(slug.current) && _id != $homepageId]{\n    "slug": slug.current\n  }\n': AllNonHomepageSlugsQueryResult;
    '\n  *[_type == "websitePage" && defined(slug.current) && seo.noIndex != true]\n    | order(_updatedAt desc) {\n    "slug": slug.current,\n    "lastModified": _updatedAt,\n    "isHomepage": _id == $homepageId\n  }\n': AllWebsitePagesForSitemapQueryResult;
    '\n  *[_type == "redirect" && defined(from) && defined(to)]{\n    from,\n    to,\n    redirectType\n  }\n': AllRedirectsQueryResult;
  }
}
